logging:
  level:
    root: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat_demo?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
